first commit
Custos-Diretriz/custos-mobile pull request #6
Opened 2024-10-27 11:38 UTC by od-hunter

2024-10-27 15:25 UTC, od-hunter commented
Resolves #4

2024-10-29 07:05 UTC, od-hunter commented
@Khauthymo , @Goodness5 please review

2024-10-30 11:10 UTC, Goodness5 requested changes
the flow of agreement and the screen designs do not fit in with the figma designs can you please adjust that
here is figma link in case you missed it https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=1659-3562&node-type=section&t=4hOawtXyXTHtfd44-0

also the icon on no-agreement screen isan animated icon you should see the link to the gif version on the figma to lottiefiles.com

2024-11-01 00:38 UTC, faytey commented
@od-hunter  are you still working on this issue

2024-11-01 02:24 UTC, faytey reviewed
- [ ] Kindly remove the contribution guidelines copy from the folder
- [ ] Also remove the .gitignore copy file present in your folder
- [ ] Kindly Implement all screens for the mobile app.
- [ ] Also the implementation/interaction and reading from the smart contract has not been worked on, kindly work on that.

2024-11-01 02:51 UTC, faytey commented on app/(screens)/index.tsx
Kindly remove commented blocks of code from the file

2024-11-01 04:16 UTC, od-hunter commented
> @od-hunter are you still working on this issue

Yes I am ma. Will make necessary corrections an dm push. Thanks.

2024-11-01 09:38 UTC, faytey requested changes
- [ ] Kindly remove the contribution guidelines copy from the folder
- [ ] Also remove the .gitignore copy file present in your folder
- [ ] Kindly Implement all screens for the mobile app.
- [ ] Also the implementation/interaction and reading from the smart contract has not been worked on, kindly work on that.

2024-11-01 09:40 UTC, faytey requested changes
Kindly remove commented blocks of code from the file

2024-11-02 17:07 UTC, Goodness5 commented
@od-hunter kindly note that tomorrow is the last day for the od-hack no PRs submitted after tomorrow will be considered for the od-hack

2024-11-02 17:17 UTC, od-hunter commented
> @od-hunter kindly note that tomorrow is the last day for the od-hack no PRs submitted after tomorrow will be considered for the od-hack

I’ll push a pr shortly ser, sorry for the delay please. I’m on it presently.

2024-11-02 21:21 UTC, faytey requested changes
- [ ] Awesome work, there's still seems to be some merge conflicts, please fix all merge conflicts between your branch and the base branch, then I can merge
- [ ] Also add screenshots or videos of the working app from your local machine thanks

2024-11-02 21:23 UTC, faytey requested changes
- [ ] Awesome work, there's still seems to be some merge conflicts, please fix all merge conflicts between your branch and the base branch, then I can merge

- [ ] Also add screenshots or videos of the working app from your local machine thanks

2024-11-03 03:30 UTC, od-hunter commented
Uploading 4ee22e47-06bb-4fa3-9127-4c7c453c883b.mov…

@faytey , please review

2024-11-03 03:40 UTC, od-hunter commented
https://github.com/user-attachments/assets/e57c629e-0d67-4dc9-ba35-5222cf7f1d66

@faytey , please review

2024-11-03 05:07 UTC, faytey approved these changes

2024-11-03 05:09 UTC, merged